package com.example.workschedule.domain

import com.example.workschedule.data.database.ScheduleDataBase
import com.example.workschedule.data.database.direction.DirectionEntity
import com.example.workschedule.data.database.driver.DriverEntity
import com.example.workschedule.data.database.permission.PermissionEntity

// todo ↓↓↓ Хардкод, после настройки приложения удалить ↓↓↓

const val restHours = 16  // Константа опряделяющая количество часов отдыха после работы

// Метод записи хард-кода в Базу Данных для демонстрации
suspend fun saveFakeDataToDB(database: ScheduleDataBase) {
    database.driverDao().saveDriverList(
        listOf(
            DriverEntity(1, 3602, "*Багаевский", "Николай", "Н"),
            DriverEntity(2, 8009, "*Бовдуй", "Алексей", "Н"),
            DriverEntity(3, 3721, "*Бондарев", "Александр", "А"),
            DriverEntity(4, 3560, "*Бондаренко", "Евгений", "Юрьевич"),
            DriverEntity(5, 21404, "*Бондарь", "С", "В"),
            DriverEntity(6, 22102, "*Борзов", "А", "В"),
            DriverEntity(7, 8004, "*Быковский", "В", "В"),
            DriverEntity(8, 3746, "*Варданян", "А", "В"),
            DriverEntity(9, 3112, "*Ворошилов", "А", "В"),
            DriverEntity(10, 20788, "*Гельт", "А", "П"),
            DriverEntity(11, 3167, "*Голобородько", "А", "Н"),
            DriverEntity(12, 20272, "*Жабин", "А", "Ю"),
            DriverEntity(13, 7024, "*Заика", "А", "И"),
            DriverEntity(14, 3765, "*Заноздря", "Т", "В"),
            DriverEntity(15, 2504, "*Заонегин", "В", "Ф"),
            DriverEntity(16, 3298, "*Зверяк", "В", "С"),
            DriverEntity(17, 3738, "*Зорич", "К", "Е"),
            DriverEntity(18, 8017, "*Конеев", "Э", "А"),
            DriverEntity(19, 7075, "*Коротков", "Д", "Н"),
            DriverEntity(20, 3469, "*Кравченко", "С", "Н"),
            DriverEntity(21, 20083, "*Кубрак", "Д", "В"),
            DriverEntity(22, 20118, "*Кукуяшный", "А", "В"),
            DriverEntity(23, 20363, "*Курников", "И", "К"),
            DriverEntity(24, 3617, "*Кучер", "В", "С"),
            DriverEntity(25, 20765, "*Леонов", "В", "А"),
            DriverEntity(26, 3800, "*Лопатин", "Р", "Н"),
            DriverEntity(27, 21426, "*Маликов", "А", "В"),
            DriverEntity(28, 20148, "*Мельцев", "Д", "А"),
            DriverEntity(29, 7039, "Мерненко", "Е", "И"),
            DriverEntity(30, 20775, "*Метелев", "Сергей", "В"),
            DriverEntity(31, 3080, "*Михайленко", "Сергей", "Владимирович"),
            DriverEntity(32, 3501, "*Михайлин", "Евгений", "Сергеевич"),
            DriverEntity(33, 21132, "*Панаев", "Алисафа", "Б"),
            DriverEntity(34, 2586, "*Пашковский", "М", "Ю"),
            DriverEntity(35, 7085, "*Пешкевич", "А", "Г"),
            DriverEntity(36, 7043, "*Попов", "А", "А"),
            DriverEntity(37, 20100, "*Свистунов", "О", "А"),
            DriverEntity(38, 3300, "*Скачко", "В", "Н"),
            DriverEntity(39, 3656, "*Скрипников", "С", "А"),
            DriverEntity(40, 3460, "*Сундуков", "Н", "В"),
            DriverEntity(41, 3980, "*Тимофеев", "И", "В"),
            DriverEntity(42, 3077, "*Ткаченко", "И", "Г"),
            DriverEntity(43, 1166, "*Устюжанин", "И", "Н"),
            DriverEntity(44, 6628, "*Фролов", "Роман", "В"),
            DriverEntity(45, 8066, "*Чакин", "С", "П"),
            DriverEntity(46, 21177, "*Шувалов", "Ю", "Н"),
            DriverEntity(47, 3094, "*Шугайлов", "В", "В"),
            DriverEntity(48, 21673, "*Бабенко", "М", "В"),
            DriverEntity(49, 6503, "*Бабешко", "Е", "В"),
            DriverEntity(50, 3132, "*Василеев", "А", "Ю"),
            DriverEntity(51, 21066, "*Головкин", "А", "Г"),
            DriverEntity(52, 2558, "*Голубов", "С", "В"),
            DriverEntity(53, 3921, "*Гордеев", "Н", "А"),
            DriverEntity(54, 3144, "*Гудзенко", "М", "Ю"),
            DriverEntity(55, 7021, "*Донцов", "А", "В"),
            DriverEntity(56, 20372, "*Евсеенко", "С", "В"),
            DriverEntity(57, 3490, "*Егоров", "В", "В"),
            DriverEntity(58, 3509, "*Жатов", "А", "В"),
            DriverEntity(59, 8008, "*Загоруйко", "В", "Н"),
            DriverEntity(60, 710, "*Захаров", "Д", "С"),
            DriverEntity(61, 3322, "*Зинченко", "Д", "А"),
            DriverEntity(62, 6611, "*Золотарев", "К", "А"),
            DriverEntity(63, 21110, "*Иващенко", "Н", "А"),
            DriverEntity(64, 21175, "*Капрал", "Роман", "В"),
            DriverEntity(65, 3181, "*Коньшин", "А", "В"),
            DriverEntity(66, 20621, "*Кучеренко", "Сергей", "Федерович"),
            DriverEntity(67, 20087, "*Ларюк", "Роман", "А"),
            DriverEntity(68, 8072, "*Литвинов", "П", "В"),
            DriverEntity(69, 20095, "*Лондарев", "Дмитрий", "Юрьевич"),
            DriverEntity(70, 20178, "*Лондарев", "Иван", "Юрьевич"),
            DriverEntity(71, 3089, "*Марченко", "А", "Юрьевич"),
            DriverEntity(72, 6604, "*Махортов", "Олег", "Александрович"),
            DriverEntity(73, 3696, "*Милованов", "А", "Д"),
            DriverEntity(74, 20117, "*Норицын", "Павел", "А"),
            DriverEntity(75, 2435, "*Овчинников", "А", "С"),
            DriverEntity(76, 3543, "*Оплачко", "А", "А"),
            DriverEntity(77, 3116, "*Павлицкий", "П", "А"),
            DriverEntity(78, 3458, "*Павлов", "А", "А"),
            DriverEntity(79, 529, "*Пахомов", "С", "П"),
            DriverEntity(80, 3107, "*Пашкевич", "Александр", "А"),
            DriverEntity(81, 3519, "*Поздеев", "Юрий", "А"),
            DriverEntity(82, 3211, "*Рубанов", "С", "И"),
            DriverEntity(83, 6630, "*Рыжков", "Владимир", "В"),
            DriverEntity(84, 22232, "*Рязанов", "С", "А"),
            DriverEntity(85, 7132, "*Сафронов", "С", "М"),
            DriverEntity(86, 3688, "*Сердюк", "В", "А"),
            DriverEntity(87, 3365, "*Соловьев", "А", "С"),
            DriverEntity(88, 7048, "*Сорокин", "Николай", "М"),
            DriverEntity(89, 2019, "*Телегин", "Юрий", "Юрьевич"),
            DriverEntity(90, 3910, "*Тикунов", "А", "А"),
            DriverEntity(91, 0, "*Трошин", "А", "В"),
            DriverEntity(92, 2960, "*Четыржоков", "Роман", "Капланович"),
            DriverEntity(93, 3723, "*Чукаев", "М", "В"),
            DriverEntity(94, 2952, "*Шаблевский", "Дмитрий", "Г"),
            DriverEntity(95, 20595, "*Шатний", "А", "А"),
            DriverEntity(96, 6104, "*Шевлюков", "В", "С"),
            DriverEntity(97, 3634, "*Шимон", "В", "С"),
            DriverEntity(98, 8003, "*Басов", "В", "И"),
            DriverEntity(99, 2135, "*Басов", "И", "В"),
            DriverEntity(100, 2702, "*Иванов", "А", "Ю"),
            DriverEntity(101, 2220, "*Краснов", "А", "В"),
            DriverEntity(102, 20700, "*Нечаев", "А", "В"),
            DriverEntity(103, 20571, "*Скрипников", "С", "В"),
            DriverEntity(104, 3067, "*Голубин", "А", "Н"),
            DriverEntity(105, 3056, "*Калашников", "В", "Ю"),
            DriverEntity(106, 3744, "*Курышов", "М", "С"),
            DriverEntity(107, 3319, "*Марченко", "Юрий", "Евгениевич"),
            DriverEntity(108, 20493, "*Новрузбеков", "Г", "Н"),
            DriverEntity(109, 3023, "*Поминов", "А", "В"),
            DriverEntity(110, 21302, "*Петренко", "А", "А"),
            DriverEntity(111, 3333, "*Родичкин", "Сергей", "В"),
            DriverEntity(112, 0, "Кузнецов", "?", "?"),



            DriverEntity(113, 0, "Весторопский", "?", "?"),
            DriverEntity(114, 3642, "Котов", "?", "?"),
            DriverEntity(115, 20180, "Арзуманов", "?", "?"),
            DriverEntity(116, 8020, "Бондаренко", "С", "?"),
            DriverEntity(117, 21900, "Горобец", "?", "?"),
            DriverEntity(117, 3648, "Захарцев", "?", "?"),
            DriverEntity(117, 3811, "Игнатов", "?", "?"),
            DriverEntity(117, 2104, "Калинин", "?", "?"),
            DriverEntity(117, 20534, "Микеян", "?", "?"),
            DriverEntity(117, 20515, "Пушкарев", "?", "?"),
            DriverEntity(117, 6084, "Лавренко", "?", "?"),
            DriverEntity(117, 20245, "Дмитренко", "?", "?"),
            DriverEntity(117, 0, "Линник", "?", "?"),
            DriverEntity(117, 0, "Лесных", "?", "?"),
            DriverEntity(117, 0, "Берг", "?", "?"),
            DriverEntity(117, 20844, "Ладыгин", "?", "?"),
            DriverEntity(117, 3399, "Ландин", "?", "?"),
            DriverEntity(117, 20627, "Михайликов", "?", "?"),
            DriverEntity(117, 0, "Попов", "К", "?"),
            DriverEntity(117, 3699, "Сечко", "Виктор", "Стефанович"),
            DriverEntity(117, 3359, "Стельмашов", "?", "?"),
            DriverEntity(117, 6636, "Устинов", "?", "?"),
            DriverEntity(117, 3045, "Фадин", "?", "?"),
            DriverEntity(117, 2992, "Яицков", "Алексей", "?"),
        )
    )

    database.directionDao().saveDirections(
        listOf(
            DirectionEntity(1, "Отрожка"),
            DirectionEntity(2, "Лиски"),
            DirectionEntity(3, "Россошь ЭП1"),
            DirectionEntity(4, "Адлер"),
            DirectionEntity(5, "Горячий Ключ"),
            DirectionEntity(6, "НВРС КРС"),
            DirectionEntity(7, "НВРС Протока"),
            DirectionEntity(8, "ТМН КРС"),
            DirectionEntity(9, "ТМН Протока"),
            DirectionEntity(10, "Кисловодск"),
            DirectionEntity(11, "Мин Воды"),
            DirectionEntity(12, "Белореченск"),
            DirectionEntity(13, "Анапа КРС"),
            DirectionEntity(14, "Анапа"),
            DirectionEntity(15, "Бузинка"),
            DirectionEntity(16, "Таганрог"),
            DirectionEntity(17, "Кавказская"),
            DirectionEntity(18, "Россошь ЭП20")
        )
    )
    savePermissions(database)
}

// Метод очистки базы данных с очисткой ключей автоинкремента
fun clearDatabase(database: ScheduleDataBase) {
    database.runInTransaction {
        database.clearAllTables()
        database.openHelper.writableDatabase.execSQL("DELETE FROM sqlite_sequence")
    }
}

private suspend fun savePermissions(database: ScheduleDataBase) {
    database.permissionDao().addPermissionsToDrivers(
        listOf(
            PermissionEntity(1, 2),
            PermissionEntity(1, 3),
            PermissionEntity(1, 4),
            PermissionEntity(1, 5),
            PermissionEntity(1, 8),
            PermissionEntity(1, 9),
            PermissionEntity(1, 10),
            PermissionEntity(1, 11),
            PermissionEntity(1, 13),
            PermissionEntity(1, 14),
            PermissionEntity(1, 15),
            PermissionEntity(1, 16),
            PermissionEntity(1, 17),
            PermissionEntity(1, 18),
            PermissionEntity(2, 2),
            PermissionEntity(2, 3),
            PermissionEntity(2, 4),
            PermissionEntity(2, 5),
            PermissionEntity(2, 6),
            PermissionEntity(2, 7),
            PermissionEntity(2, 8),
            PermissionEntity(2, 9),
            PermissionEntity(2, 13),
            PermissionEntity(2, 14),
            PermissionEntity(2, 16),
            PermissionEntity(2, 18),
            PermissionEntity(3, 1),
            PermissionEntity(3, 2),
            PermissionEntity(3, 3),
            PermissionEntity(3, 4),
            PermissionEntity(3, 5),
            PermissionEntity(3, 8),
            PermissionEntity(3, 15),
            PermissionEntity(3, 16),
            PermissionEntity(3, 18),
            PermissionEntity(4, 2),
            PermissionEntity(4, 3),
            PermissionEntity(4, 4),
            PermissionEntity(4, 5),
            PermissionEntity(4, 6),
            PermissionEntity(4, 7),
            PermissionEntity(4, 8),
            PermissionEntity(4, 9),
            PermissionEntity(4, 15),
            PermissionEntity(4, 18),
            PermissionEntity(5, 1),
            PermissionEntity(5, 2),
            PermissionEntity(5, 3),
            PermissionEntity(5, 4),
            PermissionEntity(5, 5),
            PermissionEntity(5, 6),
            PermissionEntity(5, 7),
            PermissionEntity(5, 8),
            PermissionEntity(5, 9),
            PermissionEntity(5, 10),
            PermissionEntity(5, 11),
            PermissionEntity(5, 13),
            PermissionEntity(5, 14),
            PermissionEntity(5, 18),
            PermissionEntity(6, 2),
            PermissionEntity(6, 3),
            PermissionEntity(6, 4),
            PermissionEntity(6, 5),
            PermissionEntity(6, 6),
            PermissionEntity(6, 7),
            PermissionEntity(6, 8),
            PermissionEntity(6, 9),
            PermissionEntity(6, 16),
            PermissionEntity(6, 18),
            PermissionEntity(7, 1),
            PermissionEntity(7, 2),
            PermissionEntity(7, 3),
            PermissionEntity(7, 4),
            PermissionEntity(7, 5),
            PermissionEntity(7, 10),
            PermissionEntity(7, 11),
            PermissionEntity(7, 16),
            PermissionEntity(7, 18),
            PermissionEntity(8, 1),
            PermissionEntity(8, 2),
            PermissionEntity(8, 3),
            PermissionEntity(8, 4),
            PermissionEntity(8, 5),
            PermissionEntity(8, 6),
            PermissionEntity(8, 7),
            PermissionEntity(8, 8),
            PermissionEntity(8, 9),
            PermissionEntity(8, 12),
            PermissionEntity(8, 18),
            PermissionEntity(9, 1),
            PermissionEntity(9, 2),
            PermissionEntity(9, 3),
            PermissionEntity(9, 4),
            PermissionEntity(9, 5),
            PermissionEntity(9, 6),
            PermissionEntity(9, 7),
            PermissionEntity(9, 8),
            PermissionEntity(9, 9),
            PermissionEntity(9, 10),
            PermissionEntity(9, 11),
            PermissionEntity(9, 13),
            PermissionEntity(9, 14),
            PermissionEntity(9, 16),
            PermissionEntity(9, 18),
            PermissionEntity(10, 1),
            PermissionEntity(10, 2),
            PermissionEntity(10, 3),
            PermissionEntity(10, 4),
            PermissionEntity(10, 5),
            PermissionEntity(10, 6),
            PermissionEntity(10, 7),
            PermissionEntity(10, 8),
            PermissionEntity(10, 9),
            PermissionEntity(10, 18),
            PermissionEntity(11, 1),
            PermissionEntity(11, 2),
            PermissionEntity(11, 3),
            PermissionEntity(11, 4),
            PermissionEntity(11, 5),
            PermissionEntity(11, 6),
            PermissionEntity(11, 7),
            PermissionEntity(11, 8),
            PermissionEntity(11, 9),
            PermissionEntity(11, 10),
            PermissionEntity(11, 10),
            PermissionEntity(11, 16),
            PermissionEntity(11, 18),
            PermissionEntity(12, 2),
            PermissionEntity(12, 3),
            PermissionEntity(12, 4),
            PermissionEntity(12, 5),
            PermissionEntity(12, 6),
            PermissionEntity(12, 7),
            PermissionEntity(12, 8),
            PermissionEntity(12, 9),
            PermissionEntity(12, 10),
            PermissionEntity(12, 11),
            PermissionEntity(12, 16),
            PermissionEntity(12, 18),
            PermissionEntity(13, 2),
            PermissionEntity(13, 3),
            PermissionEntity(13, 5),
            PermissionEntity(13, 6),
            PermissionEntity(13, 7),
            PermissionEntity(13, 8),
            PermissionEntity(13, 9),
            PermissionEntity(13, 15),
            PermissionEntity(13, 16),
            PermissionEntity(13, 18),
            PermissionEntity(14, 1),
            PermissionEntity(14, 2),
            PermissionEntity(14, 3),
            PermissionEntity(14, 4),
            PermissionEntity(14, 5),
            PermissionEntity(14, 6),
            PermissionEntity(14, 7),
            PermissionEntity(14, 8),
            PermissionEntity(14, 9),
            PermissionEntity(14, 10),
            PermissionEntity(14, 11),
            PermissionEntity(14, 18),
            PermissionEntity(15, 2),
            PermissionEntity(15, 3),
            PermissionEntity(15, 4),
            PermissionEntity(15, 5),
            PermissionEntity(15, 6),
            PermissionEntity(15, 7),
            PermissionEntity(15, 8),
            PermissionEntity(15, 9),
            PermissionEntity(15, 10),
            PermissionEntity(15, 11),
            PermissionEntity(15, 12),
            PermissionEntity(15, 13),
            PermissionEntity(15, 14),
            PermissionEntity(15, 16),
            PermissionEntity(15, 18),
            PermissionEntity(16, 2),
            PermissionEntity(16, 3),
            PermissionEntity(16, 4),
            PermissionEntity(16, 5),
            PermissionEntity(16, 10),
            PermissionEntity(16, 11),
            PermissionEntity(16, 16),
            PermissionEntity(16, 18),
            PermissionEntity(17, 2),
            PermissionEntity(17, 3),
            PermissionEntity(17, 4),
            PermissionEntity(17, 5),
            PermissionEntity(17, 6),
            PermissionEntity(17, 7),
            PermissionEntity(17, 8),
            PermissionEntity(17, 9),
            PermissionEntity(17, 10),
            PermissionEntity(17, 11),
            PermissionEntity(17, 13),
            PermissionEntity(17, 14),
            PermissionEntity(17, 18),
            PermissionEntity(18, 2),
            PermissionEntity(18, 3),
            PermissionEntity(18, 5),
            PermissionEntity(18, 6),
            PermissionEntity(18, 7),
            PermissionEntity(18, 8),
            PermissionEntity(18, 9),
            PermissionEntity(18, 13),
            PermissionEntity(18, 14),
            PermissionEntity(18, 16),
            PermissionEntity(18, 18),
            PermissionEntity(19, 2),
            PermissionEntity(19, 3),
            PermissionEntity(19, 4),
            PermissionEntity(19, 5),
            PermissionEntity(19, 18),
            PermissionEntity(20, 1),
            PermissionEntity(20, 2),
            PermissionEntity(20, 3),
            PermissionEntity(20, 4),
            PermissionEntity(20, 5),
            PermissionEntity(20, 6),
            PermissionEntity(20, 7),
            PermissionEntity(20, 8),
            PermissionEntity(20, 9),
            PermissionEntity(20, 13),
            PermissionEntity(20, 14),
            PermissionEntity(20, 16),
            PermissionEntity(20, 18),
            PermissionEntity(21, 1),
            PermissionEntity(21, 2),
            PermissionEntity(21, 3),
            PermissionEntity(21, 4),
            PermissionEntity(21, 5),
            PermissionEntity(21, 6),
            PermissionEntity(21, 7),
            PermissionEntity(21, 8),
            PermissionEntity(21, 9),
            PermissionEntity(21, 13),
            PermissionEntity(21, 14),
            PermissionEntity(21, 16),
            PermissionEntity(21, 18),
            PermissionEntity(22, 1),
            PermissionEntity(22, 2),
            PermissionEntity(22, 3),
            PermissionEntity(22, 4),
            PermissionEntity(22, 5),
            PermissionEntity(22, 6),
            PermissionEntity(22, 7),
            PermissionEntity(22, 8),
            PermissionEntity(22, 9),
            PermissionEntity(22, 13),
            PermissionEntity(22, 14),
            PermissionEntity(22, 18),
            PermissionEntity(23, 2),
            PermissionEntity(23, 3),
            PermissionEntity(23, 4),
            PermissionEntity(23, 5),
            PermissionEntity(23, 8),
            PermissionEntity(23, 9),
            PermissionEntity(23, 16),
            PermissionEntity(23, 18),
            PermissionEntity(24, 2),
            PermissionEntity(24, 3),
            PermissionEntity(24, 4),
            PermissionEntity(24, 5),
            PermissionEntity(24, 8),
            PermissionEntity(24, 9),
            PermissionEntity(24, 12),
            PermissionEntity(24, 16),
            PermissionEntity(24, 17),
            PermissionEntity(24, 18),
            PermissionEntity(25, 2),
            PermissionEntity(25, 3),
            PermissionEntity(25, 5),
            PermissionEntity(25, 8),
            PermissionEntity(25, 9),
            PermissionEntity(25, 16),
            PermissionEntity(25, 17),
            PermissionEntity(25, 18),
            PermissionEntity(26, 2),
            PermissionEntity(26, 3),
            PermissionEntity(26, 4),
            PermissionEntity(26, 5),
            PermissionEntity(26, 18),
            PermissionEntity(27, 2),
            PermissionEntity(27, 3),
            PermissionEntity(27, 4),
            PermissionEntity(27, 5),
            PermissionEntity(27, 6),
            PermissionEntity(27, 7),
            PermissionEntity(27, 8),
            PermissionEntity(27, 9),
            PermissionEntity(27, 10),
            PermissionEntity(27, 11),
            PermissionEntity(27, 15),
            PermissionEntity(27, 18),
            PermissionEntity(28, 2),
            PermissionEntity(28, 3),
            PermissionEntity(28, 4),
            PermissionEntity(28, 5),
            PermissionEntity(28, 6),
            PermissionEntity(28, 7),
            PermissionEntity(28, 13),
            PermissionEntity(28, 14),
            PermissionEntity(28, 16),
            PermissionEntity(28, 18),
            PermissionEntity(29, 2),
            PermissionEntity(29, 3),
            PermissionEntity(29, 4),
            PermissionEntity(29, 5),
            PermissionEntity(29, 10),
            PermissionEntity(29, 11),
            PermissionEntity(29, 12),
            PermissionEntity(29, 18),
            PermissionEntity(30, 1),
            PermissionEntity(30, 2),
            PermissionEntity(30, 3),
            PermissionEntity(30, 4),
            PermissionEntity(30, 5),
            PermissionEntity(30, 10),
            PermissionEntity(30, 11),
            PermissionEntity(30, 12),
            PermissionEntity(30, 18),
            PermissionEntity(31, 1),
            PermissionEntity(31, 2),
            PermissionEntity(31, 3),
            PermissionEntity(31, 4),
            PermissionEntity(31, 5),
            PermissionEntity(31, 6),
            PermissionEntity(31, 7),
            PermissionEntity(31, 8),
            PermissionEntity(31, 9),
            PermissionEntity(31, 10),
            PermissionEntity(31, 11),
            PermissionEntity(31, 12),
            PermissionEntity(31, 13),
            PermissionEntity(31, 14),
            PermissionEntity(31, 16),
            PermissionEntity(31, 18),
            PermissionEntity(32, 2),
            PermissionEntity(32, 3),
            PermissionEntity(32, 4),
            PermissionEntity(32, 5),
            PermissionEntity(32, 6),
            PermissionEntity(32, 7),
            PermissionEntity(32, 8),
            PermissionEntity(32, 9),
            PermissionEntity(32, 13),
            PermissionEntity(32, 14),
            PermissionEntity(32, 18),
            PermissionEntity(33, 2),
            PermissionEntity(33, 3),
            PermissionEntity(33, 4),
            PermissionEntity(33, 5),
            PermissionEntity(33, 6),
            PermissionEntity(33, 7),
            PermissionEntity(33, 8),
            PermissionEntity(33, 9),
            PermissionEntity(33, 16),
            PermissionEntity(33, 18),
            PermissionEntity(34, 2),
            PermissionEntity(34, 3),
            PermissionEntity(34, 4),
            PermissionEntity(34, 5),
            PermissionEntity(34, 6),
            PermissionEntity(34, 7),
            PermissionEntity(34, 8),
            PermissionEntity(34, 9),
            PermissionEntity(34, 16),
            PermissionEntity(34, 18),
            PermissionEntity(35, 2),
            PermissionEntity(35, 3),
            PermissionEntity(35, 4),
            PermissionEntity(35, 5),
            PermissionEntity(35, 15),
            PermissionEntity(35, 16),
            PermissionEntity(35, 18),
            PermissionEntity(36, 2),
            PermissionEntity(36, 3),
            PermissionEntity(36, 4),
            PermissionEntity(36, 5),
            PermissionEntity(36, 11),
            PermissionEntity(36, 16),
            PermissionEntity(36, 18),
            PermissionEntity(37, 2),
            PermissionEntity(37, 3),
            PermissionEntity(37, 4),
            PermissionEntity(37, 5),
            PermissionEntity(37, 6),
            PermissionEntity(37, 16),
            PermissionEntity(37, 18),
            PermissionEntity(38, 2),
            PermissionEntity(38, 3),
            PermissionEntity(38, 5),
            PermissionEntity(38, 8),
            PermissionEntity(38, 9),
            PermissionEntity(38, 16),
            PermissionEntity(38, 18),
            PermissionEntity(39, 2),
            PermissionEntity(39, 3),
            PermissionEntity(39, 4),
            PermissionEntity(39, 5),
            PermissionEntity(39, 8),
            PermissionEntity(39, 9),
            PermissionEntity(39, 15),
            PermissionEntity(39, 18),
            PermissionEntity(40, 2),
            PermissionEntity(40, 3),
            PermissionEntity(40, 4),
            PermissionEntity(40, 5),
            PermissionEntity(40, 6),
            PermissionEntity(40, 7),
            PermissionEntity(40, 18),
            PermissionEntity(41, 1),
            PermissionEntity(41, 2),
            PermissionEntity(41, 3),
            PermissionEntity(41, 4),
            PermissionEntity(41, 5),
            PermissionEntity(41, 6),
            PermissionEntity(41, 7),
            PermissionEntity(41, 8),
            PermissionEntity(41, 9),
            PermissionEntity(41, 10),
            PermissionEntity(41, 11),
            PermissionEntity(41, 12),
            PermissionEntity(41, 16),
            PermissionEntity(41, 18),
            PermissionEntity(42, 1),
            PermissionEntity(42, 2),
            PermissionEntity(42, 3),
            PermissionEntity(42, 4),
            PermissionEntity(42, 5),
            PermissionEntity(42, 16),
            PermissionEntity(42, 18),
            PermissionEntity(43, 2),
            PermissionEntity(43, 3),
            PermissionEntity(43, 4),
            PermissionEntity(43, 5),
            PermissionEntity(43, 10),
            PermissionEntity(43, 11),
            PermissionEntity(43, 12),
            PermissionEntity(43, 18),
            PermissionEntity(44, 2),
            PermissionEntity(44, 3),
            PermissionEntity(44, 4),
            PermissionEntity(44, 5),
            PermissionEntity(44, 6),
            PermissionEntity(44, 7),
            PermissionEntity(44, 8),
            PermissionEntity(44, 9),
            PermissionEntity(44, 13),
            PermissionEntity(44, 14),
            PermissionEntity(44, 16),
            PermissionEntity(44, 18),
            PermissionEntity(45, 1),
            PermissionEntity(45, 2),
            PermissionEntity(45, 3),
            PermissionEntity(45, 4),
            PermissionEntity(45, 5),
            PermissionEntity(45, 6),
            PermissionEntity(45, 7),
            PermissionEntity(45, 8),
            PermissionEntity(45, 9),
            PermissionEntity(45, 13),
            PermissionEntity(45, 14),
            PermissionEntity(45, 16),
            PermissionEntity(45, 18),
            PermissionEntity(46, 2),
            PermissionEntity(46, 3),
            PermissionEntity(46, 4),
            PermissionEntity(46, 5),
            PermissionEntity(46, 15),
            PermissionEntity(46, 16),
            PermissionEntity(46, 18),
            PermissionEntity(47, 2),
            PermissionEntity(47, 3),
            PermissionEntity(47, 4),
            PermissionEntity(47, 5),
            PermissionEntity(47, 8),
            PermissionEntity(47, 9),
            PermissionEntity(47, 15),
            PermissionEntity(47, 18),
            PermissionEntity(48, 2),
            PermissionEntity(48, 3),
            PermissionEntity(48, 10),
            PermissionEntity(48, 11),
            PermissionEntity(48, 12),
            PermissionEntity(48, 16),
            PermissionEntity(48, 18),
            PermissionEntity(49, 2),
            PermissionEntity(49, 3),
            PermissionEntity(49, 11),
            PermissionEntity(49, 18),
            PermissionEntity(50, 1),
            PermissionEntity(50, 2),
            PermissionEntity(50, 3),
            PermissionEntity(50, 16),
            PermissionEntity(50, 18),
            PermissionEntity(51, 1),
            PermissionEntity(51, 2),
            PermissionEntity(51, 3),
            PermissionEntity(51, 6),
            PermissionEntity(51, 7),
            PermissionEntity(51, 8),
            PermissionEntity(51, 9),
            PermissionEntity(51, 18),
            PermissionEntity(52, 2),
            PermissionEntity(52, 3),
            PermissionEntity(52, 6),
            PermissionEntity(52, 7),
            PermissionEntity(52, 8),
            PermissionEntity(52, 9),
            PermissionEntity(52, 10),
            PermissionEntity(52, 11),
            PermissionEntity(52, 12),
            PermissionEntity(52, 18),
            PermissionEntity(53, 2),
            PermissionEntity(53, 3),
            PermissionEntity(53, 16),
            PermissionEntity(53, 18),
            PermissionEntity(54, 2),
            PermissionEntity(54, 3),
            PermissionEntity(54, 10),
            PermissionEntity(54, 11),
            PermissionEntity(54, 12),
            PermissionEntity(54, 16),
            PermissionEntity(54, 18),
            PermissionEntity(55, 2),
            PermissionEntity(55, 3),
            PermissionEntity(55, 6),
            PermissionEntity(55, 7),
            PermissionEntity(55, 18),
            PermissionEntity(56, 2),
            PermissionEntity(56, 3),
            PermissionEntity(56, 16),
            PermissionEntity(56, 18),
            PermissionEntity(57, 1),
            PermissionEntity(57, 2),
            PermissionEntity(57, 3),
            PermissionEntity(57, 6),
            PermissionEntity(57, 7),
            PermissionEntity(57, 8),
            PermissionEntity(57, 9),
            PermissionEntity(57, 13),
            PermissionEntity(57, 14),
            PermissionEntity(57, 16),
            PermissionEntity(57, 18),
            PermissionEntity(58, 2),
            PermissionEntity(58, 3),
            PermissionEntity(58, 10),
            PermissionEntity(58, 11),
            PermissionEntity(58, 12),
            PermissionEntity(58, 18),
            PermissionEntity(59, 2),
            PermissionEntity(59, 3),
            PermissionEntity(59, 8),
            PermissionEntity(59, 9),
            PermissionEntity(59, 16),
            PermissionEntity(59, 18),
            PermissionEntity(60, 2),
            PermissionEntity(60, 3),
            PermissionEntity(60, 8),
            PermissionEntity(60, 9),
            PermissionEntity(60, 13),
            PermissionEntity(60, 14),
            PermissionEntity(60, 16),
            PermissionEntity(60, 18),
            PermissionEntity(61, 2),
            PermissionEntity(61, 3),
            PermissionEntity(61, 16),
            PermissionEntity(61, 18),
            PermissionEntity(62, 2),
            PermissionEntity(62, 3),
            PermissionEntity(62, 6),
            PermissionEntity(62, 7),
            PermissionEntity(62, 8),
            PermissionEntity(62, 9),
            PermissionEntity(62, 16),
            PermissionEntity(62, 18),
            PermissionEntity(63, 2),
            PermissionEntity(63, 3),
            PermissionEntity(63, 18),
            PermissionEntity(64, 2),
            PermissionEntity(64, 3),
            PermissionEntity(64, 6),
            PermissionEntity(64, 7),
            PermissionEntity(64, 8),
            PermissionEntity(64, 9),
            PermissionEntity(64, 12),
            PermissionEntity(64, 13),
            PermissionEntity(64, 14),
            PermissionEntity(64, 16),
            PermissionEntity(64, 18),
            PermissionEntity(65, 2),
            PermissionEntity(65, 3),
            PermissionEntity(65, 8),
            PermissionEntity(65, 9),
            PermissionEntity(65, 16),
            PermissionEntity(65, 18),
            PermissionEntity(66, 2),
            PermissionEntity(66, 3),
            PermissionEntity(66, 6),
            PermissionEntity(66, 7),
            PermissionEntity(66, 8),
            PermissionEntity(66, 9),
            PermissionEntity(66, 16),
            PermissionEntity(66, 18),
            PermissionEntity(67, 2),
            PermissionEntity(67, 3),
            PermissionEntity(67, 11),
            PermissionEntity(67, 18),
            PermissionEntity(68, 2),
            PermissionEntity(68, 3),
            PermissionEntity(68, 6),
            PermissionEntity(68, 7),
            PermissionEntity(68, 8),
            PermissionEntity(68, 9),
            PermissionEntity(68, 13),
            PermissionEntity(68, 14),
            PermissionEntity(68, 16),
            PermissionEntity(68, 18),
            PermissionEntity(69, 2),
            PermissionEntity(69, 3),
            PermissionEntity(69, 10),
            PermissionEntity(69, 11),
            PermissionEntity(69, 16),
            PermissionEntity(69, 18),
            PermissionEntity(70, 1),
            PermissionEntity(70, 2),
            PermissionEntity(70, 3),
            PermissionEntity(70, 10),
            PermissionEntity(70, 11),
            PermissionEntity(70, 18),
            PermissionEntity(71, 2),
            PermissionEntity(71, 3),
            PermissionEntity(71, 6),
            PermissionEntity(71, 7),
            PermissionEntity(71, 8),
            PermissionEntity(71, 9),
            PermissionEntity(71, 16),
            PermissionEntity(71, 18),
            PermissionEntity(72, 1),
            PermissionEntity(72, 2),
            PermissionEntity(72, 3),
            PermissionEntity(72, 8),
            PermissionEntity(72, 9),
            PermissionEntity(72, 18),
            PermissionEntity(73, 2),
            PermissionEntity(73, 3),
            PermissionEntity(73, 8),
            PermissionEntity(73, 9),
            PermissionEntity(73, 16),
            PermissionEntity(73, 18),
            PermissionEntity(74, 2),
            PermissionEntity(74, 3),
            PermissionEntity(74, 8),
            PermissionEntity(74, 9),
            PermissionEntity(74, 13),
            PermissionEntity(74, 14),
            PermissionEntity(74, 16),
            PermissionEntity(74, 18),
            PermissionEntity(75, 2),
            PermissionEntity(75, 3),
            PermissionEntity(75, 6),
            PermissionEntity(75, 8),
            PermissionEntity(75, 9),
            PermissionEntity(75, 10),
            PermissionEntity(75, 11),
            PermissionEntity(75, 16),
            PermissionEntity(75, 18),
            PermissionEntity(76, 1),
            PermissionEntity(76, 2),
            PermissionEntity(76, 3),
            PermissionEntity(76, 4),
            PermissionEntity(76, 10),
            PermissionEntity(76, 11),
            PermissionEntity(76, 16),
            PermissionEntity(76, 18),
            PermissionEntity(77, 2),
            PermissionEntity(77, 3),
            PermissionEntity(77, 8),
            PermissionEntity(77, 9),
            PermissionEntity(77, 18),
            PermissionEntity(78, 1),
            PermissionEntity(78, 2),
            PermissionEntity(78, 3),
            PermissionEntity(78, 6),
            PermissionEntity(78, 7),
            PermissionEntity(78, 8),
            PermissionEntity(78, 9),
            PermissionEntity(78, 13),
            PermissionEntity(78, 16),
            PermissionEntity(78, 18),
            PermissionEntity(79, 2),
            PermissionEntity(79, 3),
            PermissionEntity(79, 8),
            PermissionEntity(79, 9),
            PermissionEntity(79, 18),
            PermissionEntity(80, 2),
            PermissionEntity(80, 3),
            PermissionEntity(80, 18),
            PermissionEntity(81, 1),
            PermissionEntity(81, 2),
            PermissionEntity(81, 3),
            PermissionEntity(81, 8),
            PermissionEntity(81, 9),
            PermissionEntity(81, 11),
            PermissionEntity(81, 13),
            PermissionEntity(81, 14),
            PermissionEntity(81, 16),
            PermissionEntity(81, 18),
            PermissionEntity(82, 2),
            PermissionEntity(82, 3),
            PermissionEntity(82, 10),
            PermissionEntity(82, 11),
            PermissionEntity(82, 16),
            PermissionEntity(82, 17),
            PermissionEntity(82, 18),
            PermissionEntity(83, 2),
            PermissionEntity(83, 3),
            PermissionEntity(83, 6),
            PermissionEntity(83, 10),
            PermissionEntity(83, 11),
            PermissionEntity(83, 12),
            PermissionEntity(83, 16),
            PermissionEntity(83, 18),
            PermissionEntity(84, 2),
            PermissionEntity(84, 3),
            PermissionEntity(84, 18),
            PermissionEntity(85, 2),
            PermissionEntity(85, 3),
            PermissionEntity(85, 8),
            PermissionEntity(85, 9),
            PermissionEntity(85, 11),
            PermissionEntity(85, 12),
            PermissionEntity(85, 18),
            PermissionEntity(86, 2),
            PermissionEntity(86, 3),
            PermissionEntity(86, 8),
            PermissionEntity(86, 9),
            PermissionEntity(86, 10),
            PermissionEntity(86, 11),
            PermissionEntity(86, 16),
            PermissionEntity(86, 18),
            PermissionEntity(87, 2),
            PermissionEntity(87, 3),
            PermissionEntity(87, 18),
            PermissionEntity(88, 2),
            PermissionEntity(88, 3),
            PermissionEntity(88, 8),
            PermissionEntity(88, 9),
            PermissionEntity(88, 18),
            PermissionEntity(89, 2),
            PermissionEntity(89, 3),
            PermissionEntity(89, 18),
            PermissionEntity(90, 1),
            PermissionEntity(90, 2),
            PermissionEntity(90, 3),
            PermissionEntity(90, 16),
            PermissionEntity(90, 18),
            PermissionEntity(91, 2),
            PermissionEntity(91, 3),
            PermissionEntity(91, 8),
            PermissionEntity(91, 9),
            PermissionEntity(91, 10),
            PermissionEntity(91, 11),
            PermissionEntity(91, 12),
            PermissionEntity(91, 16),
            PermissionEntity(91, 18),
            PermissionEntity(92, 2),
            PermissionEntity(92, 3),
            PermissionEntity(92, 6),
            PermissionEntity(92, 7),
            PermissionEntity(92, 8),
            PermissionEntity(92, 9),
            PermissionEntity(92, 13),
            PermissionEntity(92, 14),
            PermissionEntity(92, 16),
            PermissionEntity(92, 18),
            PermissionEntity(93, 2),
            PermissionEntity(93, 3),
            PermissionEntity(93, 18),
            PermissionEntity(94, 2),
            PermissionEntity(94, 3),
            PermissionEntity(94, 18),
            PermissionEntity(95, 2),
            PermissionEntity(95, 3),
            PermissionEntity(95, 6),
            PermissionEntity(95, 7),
            PermissionEntity(95, 8),
            PermissionEntity(95, 9),
            PermissionEntity(95, 13),
            PermissionEntity(95, 14),
            PermissionEntity(95, 16),
            PermissionEntity(95, 18),
            PermissionEntity(96, 2),
            PermissionEntity(96, 3),
            PermissionEntity(96, 6),
            PermissionEntity(96, 7),
            PermissionEntity(96, 8),
            PermissionEntity(96, 9),
            PermissionEntity(96, 13),
            PermissionEntity(96, 16),
            PermissionEntity(96, 18),
            PermissionEntity(97, 2),
            PermissionEntity(97, 3),
            PermissionEntity(97, 8),
            PermissionEntity(97, 9),
            PermissionEntity(97, 16),
            PermissionEntity(97, 18),
            PermissionEntity(98, 2),
            PermissionEntity(98, 3),
            PermissionEntity(98, 4),
            PermissionEntity(98, 5),
            PermissionEntity(98, 8),
            PermissionEntity(98, 16),
            PermissionEntity(98, 18),
            PermissionEntity(99, 1),
            PermissionEntity(99, 2),
            PermissionEntity(99, 3),
            PermissionEntity(99, 16),
            PermissionEntity(99, 18),
            PermissionEntity(100, 3),
            PermissionEntity(100, 5),
            PermissionEntity(100, 16),
            PermissionEntity(101, 3),
            PermissionEntity(101, 5),
            PermissionEntity(101, 15),
            PermissionEntity(102, 3),
            PermissionEntity(102, 5),
            PermissionEntity(102, 15),
            PermissionEntity(103, 3),
            PermissionEntity(103, 5),
            PermissionEntity(103, 16),
            PermissionEntity(104, 3),
            PermissionEntity(104, 16),
            PermissionEntity(105, 3),
            PermissionEntity(105, 16),
            PermissionEntity(106, 3),
            PermissionEntity(106, 16),
            PermissionEntity(107, 3),
            PermissionEntity(107, 16),
            PermissionEntity(108, 3),
            PermissionEntity(109, 3),
            PermissionEntity(110, 4),
            PermissionEntity(110, 5),
            PermissionEntity(110, 6),
            PermissionEntity(110, 7),
            PermissionEntity(110, 8),
            PermissionEntity(110, 9),
            PermissionEntity(110, 10),
            PermissionEntity(110, 11),
            PermissionEntity(110, 17),
            PermissionEntity(110, 18),
            PermissionEntity(111, 6),
            PermissionEntity(111, 7),
            PermissionEntity(111, 8),
            PermissionEntity(111, 9),
            PermissionEntity(111, 13),
            PermissionEntity(111, 14),
            PermissionEntity(111, 18),
            PermissionEntity(112, 3)
        )
    )
}


// todo ↑↑↑ Хардкод, после настройки приложения удалить ↑↑↑